"""Generate a printable PDF of a quiz using ReportLab."""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

_BLOOM_COLOR = colors.HexColor("#3b6ea5")


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("title", parent=base["Title"], fontSize=20, spaceAfter=4),
        "meta": ParagraphStyle("meta", parent=base["Normal"], fontSize=9, textColor=colors.grey),
        "section": ParagraphStyle("section", parent=base["Heading2"], fontSize=13,
                                  textColor=_BLOOM_COLOR, spaceBefore=10, spaceAfter=6),
        "q": ParagraphStyle("q", parent=base["Normal"], fontSize=11, spaceBefore=8,
                            spaceAfter=2, leading=15),
        "opt": ParagraphStyle("opt", parent=base["Normal"], fontSize=10, leftIndent=14, leading=14),
        "tag": ParagraphStyle("tag", parent=base["Normal"], fontSize=8, textColor=colors.grey),
        "ans": ParagraphStyle("ans", parent=base["Normal"], fontSize=10, leading=14),
    }
    return styles


def build_quiz_pdf(quiz: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=18 * mm, rightMargin=18 * mm, title=quiz["title"],
    )
    s = _styles()
    story = []

    story.append(Paragraph(quiz["title"], s["title"]))
    meta_bits = []
    if quiz.get("subject"):
        meta_bits.append(f"Subject: {quiz['subject']}")
    if quiz.get("topic"):
        meta_bits.append(f"Topic: {quiz['topic']}")
    meta_bits.append(f"Difficulty: {quiz.get('difficulty', 'Medium')}")
    meta_bits.append(f"Questions: {len(quiz['questions'])}")
    story.append(Paragraph(" &nbsp;|&nbsp; ".join(meta_bits), s["meta"]))
    story.append(Paragraph("Generated by AI Quiz Generator", s["meta"]))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=colors.lightgrey))

    letters = ["A", "B", "C", "D", "E"]

    # Questions section
    story.append(Paragraph("Questions", s["section"]))
    for i, q in enumerate(quiz["questions"], 1):
        story.append(Paragraph(f"<b>{i}.</b> {q['text']}", s["q"]))
        tag = f"[{q.get('bloom_level','')}] [{q.get('difficulty','')}] [{q.get('qtype','')}]"
        story.append(Paragraph(tag, s["tag"]))
        for j, opt in enumerate(q.get("options", [])):
            story.append(Paragraph(f"{letters[j]}. {opt}", s["opt"]))

    # Answer key section
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.lightgrey))
    story.append(Paragraph("Answer Key &amp; Explanations", s["section"]))
    for i, q in enumerate(quiz["questions"], 1):
        story.append(Paragraph(f"<b>{i}.</b> Answer: <b>{q.get('correct_answer','')}</b>", s["ans"]))
        if q.get("explanation"):
            story.append(Paragraph(f"<i>Explanation:</i> {q['explanation']}", s["ans"]))
        story.append(Spacer(1, 4))

    doc.build(story)
    return buf.getvalue()
